name: Generate Snake Animation

on:
  # Schedule the workflow to run daily at midnight UTC
  schedule:
    - cron: "0 */12 * * *" # runs every 12 hours
  # Allow manual triggering of the workflow
  workflow_dispatch:
  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2
      # Step 2: Generate the snake animations
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@master
        id: snake-gif
        with:
          # GitHub username to generate the animation for
          github_user_name: mintiensq
          gif_out_path: dist/github-snake.gif
          svg_out_path: dist/github-snake.svg
          svg_out_path_dark: dist/github-snake-dark.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Step 3: Deploy the generated files to the 'output' branch
      - name: Deploy to Output Branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}